import {assetUrl} from '../../shared/assetUrl';
'use client';
import {useState,useEffect,useMemo,useRef} from 'react';
import {ArrowDownToLine,RotateCcw,Box,Move3D,Play,ChevronLeft,ChevronRight,ExternalLink} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {createModel,defaults,assumptions} from '@/cases/bridge/model.mjs';
import BridgeView,{download} from './BridgeView';
import ConceptCard from '@/shared/ConceptCard';
import CaseToolbar from '@/shared/CaseToolbar';
function Choice({label,value,onChange,options}:any){return <div className="field"><label>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l]:any)=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select></div>;}
function Range({label,value,min,max,step=1,onChange,unit}:any){return <div className="range"><div><label>{label}</label><output>{value}{unit}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/><div className="range-extents"><span>{min}{unit}</span><span>{max}{unit}</span></div></div>;}
function Toggle({label,value,onChange}:any){return <div className="toggle"><label>{label}</label><Switch aria-label={label} checked={value} onCheckedChange={onChange}/></div>;}
const fmt=(n:number,d=1)=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
export default function Home(){
 const [p,setP]=useState({...defaults,selectedNode:13}),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[revision,setRevision]=useState(0);
 const [view,setView]=useState({mode:'hierarchy',deformed:false,ghost:true,scale:100,deck:true,nodes:false,loads:false,clearance:false,region:'all',selected:13});
 const [representation,setRepresentation]=useState('geometry');
 const setMode=(v:string)=>{setRepresentation(v);setView(q=>({...q,mode:v==='response'?'stress':'hierarchy',deformed:v==='response',nodes:v==='structure',loads:v==='structure',ghost:v==='response'}));};
 const [activeCamera,setActiveCamera]=useState('reference');const api=useRef<any>(null),worker=useRef<Worker|null>(null),job=useRef(0),workerBusy=useRef(false);
 const model=useMemo(()=>createModel(p),[p]);
 const update=(k:string,v:any)=>setP(q=>({...q,[k]:v}));const show=(k:string,v:any)=>{if((k==='deformed'&&v)||(k==='mode'&&v!=='hierarchy'))setRepresentation('response');setView(q=>({...q,[k]:v}));};
 const select=(id:number)=>{show('selected',id);if(p.nodeLoad)update('selectedNode',id);};
 useEffect(()=>{
  setResult(null);setBusy(true);setError('');const id=++job.current;
  // A running solve is synchronous inside its worker; termination cancels stale slider jobs.
  if(workerBusy.current){worker.current?.terminate();worker.current=null;workerBusy.current=false;}
  const timer=setTimeout(()=>{
   const w=worker.current||new Worker(assetUrl('cases/bridge/worker.mjs'),{type:'module'});worker.current=w;
   w.onmessage=({data})=>{if(data.id!==job.current)return;workerBusy.current=false;setBusy(false);if(data.error){setError(data.error);setResult(null);}else{setError('');setResult(data.result);}};
   w.onerror=()=>{workerBusy.current=false;setError('The analysis worker could not run. Reload the page to retry.');setBusy(false);};
   workerBusy.current=true;w.postMessage({id,model});
  },300);
  return()=>clearTimeout(timer);
 },[model,revision]);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const selected=model.nodes[view.selected],nr=result?.nodes[view.selected];const connected=model.members.filter((m:any)=>m.a===view.selected||m.b===view.selected);const reaction=result?.reactions.find((r:any)=>r.node===view.selected);
 const maxForce=result?Math.max(...result.members.map((r:any)=>Math.abs(r.axialForce)))/1000:0;const worst=result?[...result.members].sort((a,b)=>b.yieldIndicator-a.yieldIndicator)[0]:null;const worstEuler=result?[...result.members].sort((a,b)=>b.eulerIndicator-a.eulerIndicator)[0]:null;
 const exportModel=()=>download(JSON.stringify({...model,visualization:{...view,note:'Deformation scale is display-only. Authored coordinates precede prestress equilibration; results include prestress and applied load.'}},null,2),'model.json');
 const exportResults=()=>{if(result)download(JSON.stringify({model,results:result,interpretation:'Elastic response. Yield and Euler ratios are screening indicators, not code checks.'},null,2),'analysis.json');};
 return <main className="lab bridge-case">

  <div className="workspace">
   <section className="workbench" aria-label="Structure and analysis results">
    <div className="scene-title"><div><div className="eyebrow">01 / BRIDGE <span> · FRAME + CABLE</span></div><h1>Twin-Arch Web Bridge</h1><p>120 m span <span>·</span> 14 m deck <span>·</span> 18 m approaches × 2</p></div><div className="model-tag"><Box size={15}/> Hybrid frame + cable</div></div>
    <CaseToolbar mode={representation} onMode={setMode}/>
    <div className="viewport"><BridgeView model={model} result={result} view={view} onSelect={select} api={api} onError={setError}/>
     <ConceptCard caseId="bridge" title="Twin-Arch Web Bridge"/>
     <div className="view-tools" aria-label="Camera presets">{[['iso','Perspective'],['side','Front'],['end','Side'],['top','Top'],['reference','Fit model'],['access','Access']].map(([v,l])=><button key={v} className={activeCamera===v?'chosen':''} onClick={()=>{setActiveCamera(v);api.current?.camera(v);}}>{l}</button>)}</div>
     <div className="scene-caption"><span>{view.deformed&&result?'DEFORMED':'UNDEFORMED'}</span>{view.deformed&&result&&<b>×{view.scale} displacement</b>}<small>Dimensions assumed from concept image</small></div>
     <div className="legend"><span className="legend-title">{view.mode==='hierarchy'?'MEMBER HIERARCHY':view.mode==='axial'?'AXIAL FORCE':'ELASTIC NORMAL STRESS / fy'}</span>{view.mode==='hierarchy'?<div className="legend-items"><span><i style={{background:'#75dcdf'}}/>Primary arches</span><span><i style={{background:'#c5f0df'}}/>Arch interior</span><span><i style={{background:'#a4bacb'}}/>Deck</span><span><i style={{background:'#c4a783'}}/>Tensile web</span><span><i style={{background:'#94b8ce'}}/>Woven ends</span><span><i style={{background:'#8ca6ae'}}/>Fine lattice</span></div>:<><div className={'colorbar '+(view.mode==='axial'?'diverging':'')}/><div className="legend-values"><span>{view.mode==='axial'?`−${fmt(maxForce,0)} kN · compression`:'0'}</span><span>{view.mode==='axial'?`+${fmt(maxForce,0)} kN · tension`:'≥ 1'}</span></div></>}</div>
     <div className="orbit-hint">Drag to orbit · Scroll to zoom · Click a member or node to inspect</div>
    </div>
    <div className="results-strip" aria-live="polite"><div><span>MAX DECK DISPLACEMENT</span><strong>{result?fmt((result.maxDeckDisplacement??result.maxDisplacement)*1000):'—'}<small> mm</small></strong><p>Includes prestress equilibration</p></div><div><span>VERTICAL REACTION</span><strong>{result?fmt(result.totalReaction[1]/1000,0):'—'}<small> kN</small></strong><p>Total at all supports</p></div><div><span>PEAK NORMAL STRESS / fy</span><strong>{worst?fmt(worst.yieldIndicator,3):'—'}<small> ratio</small></strong><p>{worst?`Member ${worst.member} · elastic indicator`:'Waiting for analysis'}</p></div><div><span>ANALYSIS STATUS</span><strong className="metric-status">{error?'Error':busy?'Solving…':result?'Converged':'Ready'}</strong><p>{result?`Residual ${result.relativeResidual.toExponential(1)}`:'Hybrid frame + cable'}</p></div></div>
    <details className="case-details"><summary>Model state, accessibility & interpretation</summary>    <div className="analysis-status"><span className={error?'status-error':'status-ok'}>{error?'Analysis error':busy?'Solving structure…':'Analysis complete'}</span><span>{model.nodes.length} nodes · {model.members.length} members · frame + cable DOFs</span>{result&&<span>Residual {result.relativeResidual.toExponential(1)}</span>}</div>
    {error&&<div role="alert" className="error-box">{error}</div>}
    <div className="analysis-status">{result&&<span>Tensile web: {result.cables?.taut} taut · {result.cables?.slack} slack · Max all-node movement {fmt(result.maxDisplacement*1000)} mm{result.cableMechanisms&&' · Slack web has local free-motion modes'}</span>}</div><div className="access-note"><strong>OPEN CROSSING</strong><span>12 m clear width</span><span>5 m reserved headroom</span><span>1.35 m woven edge guards</span></div><div className="research-note"><strong>A structural interpretation of one image.</strong> Geometry, sections, materials, and restraints are assumed. Elastic frames and tension-only cables are a concept model, not a bridge safety assessment. {worstEuler&&<>Largest Euler screening ratio: {fmt(worstEuler.eulerIndicator,2)} (member {worstEuler.member}; K = 1, no global buckling).</>}</div></details>
   </section>
   <aside className="controls" aria-label="Model controls">
    <div className="panel-heading"><div className="eyebrow">EXPERIMENT CONTROLS</div><button className="icon-button" aria-label="Reset experiment" title="Reset experiment" onClick={()=>{setRepresentation('geometry');setP({...defaults,selectedNode:13});setView({mode:'hierarchy',deformed:false,ghost:true,scale:100,deck:true,nodes:false,loads:false,clearance:false,region:'all',selected:13});api.current?.camera('reference');setActiveCamera('reference');}}><RotateCcw size={17}/></button></div>
    <section className="control-section"><h2><span>01</span> Loading</h2><Choice label="Load case" value={p.loadCase} onChange={(v:string)=>update('loadCase',v)} options={ [['uniform','Full-span deck pressure'],['half','Left half-span pressure'],['point','Midspan vertical point load'],['none','Prestress only']]}/>
    {(p.loadCase==='uniform'||p.loadCase==='half')&&<Range label="Deck pressure" value={p.pressure} min={0} max={15} step={.5} onChange={(v:number)=>update('pressure',v)} unit=" kPa"/>}{p.loadCase==='point'&&<Range label="Total point load" value={p.pointLoad} min={0} max={2000} step={50} onChange={(v:number)=>update('pointLoad',v)} unit=" kN"/>}<p className="muted-note">Main span only. Downward, global −Y. Self-weight excluded.</p></section>
    <section className="control-section"><h2><span>02</span> Material & sections</h2><Range label="Young’s modulus" value={p.E} min={50} max={300} step={10} onChange={(v:number)=>update('E',v)} unit=" GPa"/><Range label="Primary section scale" value={p.primaryScale} min={.5} max={1.5} step={.05} onChange={(v:number)=>update('primaryScale',v)} unit="×"/><Range label="Secondary + fine scale" value={p.secondaryScale} min={.5} max={2} step={.05} onChange={(v:number)=>update('secondaryScale',v)} unit="×"/><Range label="Cable reference prestress" value={p.cablePrestress} min={20} max={150} step={10} unit=" MPa" onChange={(v:number)=>update('cablePrestress',v)}/><p className="muted-note">Primary: arch chords, root spines and deck. Secondary: internal braces and cables. Tube diameter/wall thickness or cable diameter scale together.</p><button className="solve-button" disabled={busy} onClick={()=>setRevision(r=>r+1)}><Play size={15}/>{busy?'Solving…':'Recalculate structure'}<span>↵</span></button><p className="auto-note">Changes recalculate automatically</p></section>
    <section className="control-section"><h2><span>03</span> Deformation / Analysis</h2><Choice label="Color by" value={view.mode} onChange={(v:string)=>show('mode',v)} options={ [['hierarchy','Member hierarchy'],['axial','Axial force'],['stress','Normal stress / yield stress']]}/><Choice label="Highlight region" value={view.region} onChange={(v:string)=>show('region',v)} options={ [['all','Entire structure'],['primary','Primary members'],['secondary','Secondary + fine members'],['tertiary','Fine distributed lattice'],['primary_arch','Thick primary arches'],['arch_internal','Arch-internal bracing'],['deck_system','Deck framing'],['cable_web','Tension-only web'],['end_support','Woven end supports'],['approach','Approaches'],['under deck','Under-deck bracing']]}/><Toggle label="Deformed configuration" value={view.deformed} onChange={(v:boolean)=>show('deformed',v)}/><Toggle label="Undeformed ghost" value={view.ghost} onChange={(v:boolean)=>show('ghost',v)}/><Range label="Deformation magnification" value={view.scale} min={1} max={300} step={1} onChange={(v:number)=>show('scale',v)} unit="×"/><Toggle label="Deck surface" value={view.deck} onChange={(v:boolean)=>show('deck',v)}/><Toggle label="Clear travel envelope" value={view.clearance} onChange={(v:boolean)=>show('clearance',v)}/><Toggle label="Node markers" value={view.nodes} onChange={(v:boolean)=>show('nodes',v)}/><Toggle label="Load arrows" value={view.loads} onChange={(v:boolean)=>show('loads',v)}/></section>
    <section className="control-section inspector"><h2>Node inspector</h2><div className="node-nav"><button aria-label="Previous node" onClick={()=>select(Math.max(0,view.selected-1))}><ChevronLeft size={18}/></button><label>Node <input aria-label="Selected node" type="number" min={0} max={model.nodes.length-1} value={view.selected} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=0&&n<model.nodes.length)select(n);}}/></label><button aria-label="Next node" onClick={()=>select(Math.min(model.nodes.length-1,view.selected+1))}><ChevronRight size={18}/></button></div><dl><dt>Region</dt><dd>{selected.region} / {selected.side?'right':'left'}</dd><dt>X, Y, Z (m)</dt><dd>{selected.position.map((v:number)=>fmt(v,1)).join(', ')}</dd><dt>Connected members</dt><dd>{connected.length}</dd><dt>Structural systems</dt><dd>{[...new Set(connected.map((m:any)=>({primary_arch:'Primary arch',arch_internal:'Arch interior',deck_system:'Deck',cable_web:'Tensile web',end_support:'Woven end'}[m.system]||m.region)))].join(', ')}</dd><dt>Displacement (mm)</dt><dd>{nr?fmt(nr.magnitude*1000,3):'—'}</dd><dt>uY (mm)</dt><dd>{nr?fmt(nr.displacement[1]*1000,3):'—'}</dd><dt>Boundary</dt><dd>{model.supports.find((s:any)=>s.node===view.selected)?.kind||(connected.every((m:any)=>m.behavior==='tension_only_cable')?'Pin joint · translations only':'Frame joint')}</dd>{reaction&&<><dt>Reaction Y (kN)</dt><dd>{fmt(reaction.force[1]/1000,2)}</dd></>}</dl><Range label="Additional node load" value={p.nodeLoad} min={0} max={500} step={25} unit=" kN" onChange={(v:number)=>setP(q=>({...q,nodeLoad:v,selectedNode:view.selected}))}/><p className="muted-note">{p.nodeLoad?`−Y load applied to node ${p.selectedNode}. Selecting another node moves this load.`:'Select a node, then add a downward point load.'}</p></section>
    <section className="control-section"><h2><span>04</span> Reset / Export</h2><button className="reset-experiment" onClick={()=>{setRepresentation('geometry');setP({...defaults,selectedNode:13});setView({mode:'hierarchy',deformed:false,ghost:true,scale:100,deck:true,nodes:false,loads:false,clearance:false,region:'all',selected:13});api.current?.camera('reference');setActiveCamera('reference');}}>Reset experiment</button><div className="export-grid"><button onClick={exportModel}><ArrowDownToLine size={15}/> Model JSON</button><button onClick={exportResults} disabled={!result}><ArrowDownToLine size={15}/> Results JSON</button><button onClick={()=>api.current?.export('glb')}><Box size={15}/> Geometry GLB</button><button onClick={()=>api.current?.export('stl')}><Box size={15}/> Geometry STL</button></div><p className="muted-note">Geometry exports use undeformed coordinates. STL units: meters; members are separate intersecting solids.</p></section>
    <section className="control-section reference"><h2>Image & interpretation</h2><a href={assetUrl("cases/bridge/reference.png")} target="_blank" rel="noreferrer"><img src={assetUrl("cases/bridge/reference.png")} alt="Supplied spider-web-inspired bridge concept with twin arches and fine web members"/><span>Original concept <ExternalLink size={13}/></span></a><details><summary>Geometric & mechanics assumptions</summary><ol>{assumptions.map((a:string)=><li key={a}>{a}</li>)}</ol><p>Euler–Bernoulli frame bending and torsion; corotational tension-only axial cables with cable slackening and cable geometric nonlinearity. Frame large-rotation effects, plasticity, fatigue, dynamics, foundation response and global buckling are omitted. Deformed members are drawn as straight segments between displaced nodes. Normal stress indicator includes axial force and end bending, but excludes shear and torsional equivalent stress.</p></details><a className="readme-link" href={assetUrl("cases/bridge/README.md")} target="_blank">Read model documentation <ExternalLink size={13}/></a></section>
   </aside>
  </div>
 </main>;
}
